# Generated by Django 4.2.16 on 2024-12-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0002_bidmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmodel",
            name="highest_bid",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="itemmodel",
            name="soldout_price",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="itemmodel",
            name="winner_name",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
