# Generated by Django 4.2.16 on 2024-12-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0003_alter_itemmodel_highest_bid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmodel",
            name="item_image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
