# Generated by Django 4.2.16 on 2024-12-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0005_usermodel_credits"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel", old_name="credits", new_name="user_credit",
        ),
    ]
