# Generated by Django 4.2.16 on 2024-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0007_alter_usermodel_user_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
