# Generated by Django 4.2.16 on 2024-12-14 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0010_alter_bidmodel_bidder_alter_bidmodel_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidmodel",
            name="bidder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="bidmodel",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auction_app.itemmodel"
            ),
        ),
    ]
