# Generated by Django 4.2.16 on 2024-12-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0014_alter_itemmodel_highest_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmodel",
            name="item_start_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="itemmodel",
            name="soldout_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
    ]
