# Generated by Django 4.2.16 on 2024-12-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0015_alter_itemmodel_item_start_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="itemmodel", name="highest_bid",),
        migrations.RemoveField(model_name="itemmodel", name="winner_name",),
        migrations.AlterField(
            model_name="itemmodel",
            name="soldout_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
