# Generated by Django 4.2.16 on 2024-12-16 10:04

import auction_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0016_remove_itemmodel_highest_bid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmodel",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                default=auction_app.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
