# Generated by Django 4.2.16 on 2024-12-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0017_alter_itemmodel_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidmodel", name="bidder", field=models.IntegerField(default=0),
        ),
    ]
